owner: cxe-miex-dev
repo: uptimes

sites:
  - name: "Paid - Panel"
    url: https://paidcxe.zxxhost.my.id/
  - name: "Paid - Node SG 1"
    check: "tcp-ping"
    url: cxenode-1.hexagonn.my.id
    port: 3306

notifications:
  - type: discord

status-website:
  cname: cxestatus.hexagonn.my.id
  logoUrl: https://cdn.discordapp.com/icons/1080420246567010304/71e27a6acae93fdb05112948eab30711.png?size=1024
  favicon: https://cdn.discordapp.com/icons/1080420246567010304/71e27a6acae93fdb05112948eab30711.png?size=1024
  name: CXE
  introTitle: "**CXE** for monitoring."
  introMessage: "Welcome to MiexCloud & CXE Status!"
  theme: night
  css: 'nav{animation:1s ease-in-out fadeInDown}main{animation:1s ease-in-out fadeIn}'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Paid - Panel
      href: https://paidcxe.zxxhost.my.id/

i18n:
  footer: "Made with 💖 by [Hexagonn](https://www.hexagonn.my.id/)"
