# Change these first
owner: cxe-miex-dev # Your GitHub organization or username, where this repository lives
repo: uptimes # The name of this repository

sites:
  - name: Panel
    url: https://dev-free.miexcloud.studio/

status-website:
  cname: uptime.scoodev.my.id
  logoUrl: https://therealzzy.xyz/icon.png
  favicon: https://therealzzy.xyz/icon.png
  name: Cxe x Miex
  introTitle: "**Cxe x Miex Uptime Status** for monitoring."
  introMessage: "You can see all my websites, api, etc. (idk) if they're online or not."
  theme: ocean
  css: 'nav{animation:1s ease-in-out fadeInDown}main{animation:1s ease-in-out fadeIn}'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://therealzzy.xyz
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
