# Change these first
owner: cxe-miex-dev # Your GitHub organization or username, where this repository lives
repo: uptimes # The name of this repository

sites:
  - name: Free-Panel
    url: https://dev-free.miexcloud.studio/
  - name: Free-node.sg.1
    check: "tcp-ping"
    url: node1.miexcloud.studio
    port: 3306
  - name: Free-node.sg.2
    check: "tcp-ping"
    url: node2.miexcloud.studio
    port: 3306

status-website:
  cname: uptime.scoodev.my.id
  logoUrl: https://raw.scoodev.my.id/miexcloud/logo.png
  favicon: https://raw.scoodev.my.id/miexcloud/logo.png
  name: Cxe x Miex
  introTitle: "**Cxe x Miex Uptime Status** for monitoring."
  introMessage: "Welcome to MiexCloud & CXE Status!"
  theme: night
  css: 'nav{animation:1s ease-in-out fadeInDown}main{animation:1s ease-in-out fadeIn}'
  links:
    - rel: stylesheet
      href: https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://dev-free.miexcloud.studio/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
